apiVersion: v1
kind: Service
metadata:
  name: {{ template "relname" . }}-admin
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ template "relname" . }}
    app.kubernetes.io/component: admin
    app.kubernetes.io/instance: {{ template "relname" . }}-admin
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: {{ template "relname" . }}
    app.kubernetes.io/managed-by: helm    
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.ports.admin }}
    protocol: TCP
    name: http-admin
  selector:
    app: {{ template "relname" . }}
    component: admin