apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "relname" . }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300s"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: dns01
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.hostnames.customer | quote }}
    secretName: {{ template "relname" . }}-customer-tls
  rules:
  - host: {{ .Values.hostnames.customer | quote }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ template "relname" . }}-customer
            port:
              number: 80