import iphone from '../../assets/infinix-note-12.png';
import laptop5 from '../../assets/laptop5.png';
import laptop6 from '../../assets/laptop6.png';
import mob1 from '../../assets/infinix-removebg-preview.png';
import mob2 from '../../assets/InfinixHot12-b.png';
import mob3 from '../../assets/InfinixNote12VIP-b.png';


export const productsData = [
    {
        id: 1,
        imageURL: iphone,
        price: "161,428 Rs.",
        name: "Apple iphone Pro 13\" 2.4 2019 Intel Core i5 DDR3 8 GB SSD 256 GB",
        description: "Intel Core i5, DDR3, 8GB RAM, 256GB SSD",
        colors: ["#a5d6a7", "#ef9a9a", "#ffcc80", "#b0bec5"],
        stock: 230,
        device: "MacBook Pro",
        installment: 30000,
        imageGallery: [mob1, mob3, mob2, mob2],
        build:"",
        processor:"",
        display:"",
        frequency:"",
        memory:"",
        camera:"",
        connectivity:"",
        builtin_feature:"",
        battery:"",
    },
    {
        id: 2,
        imageURL: laptop5,
        price: "120,000 Rs.",
        name: "Dell Inspiron 15 Intel Core i7 DDR4 16 GB SSD 512 GB",
        description: "Intel Core i7, DDR4, 16GB RAM, 512GB SSD",
        colors: ["#000000", "#ffffff"],
        stock: 100,
        device: "Dell Inspiron",
        installment: 52000,
        imageGallery: [laptop5, laptop5, laptop5, laptop5]
    },
    {
        id: 3,
        imageURL: laptop6,
        price: "90,000 Rs.",
        name: "HP Pavilion x360 Intel Core i5 DDR4 8 GB SSD 256 GB",
        description: "Intel Core i7, DDR4, 16GB RAM, 512GB SSD",
        colors: ["#000000", "#ffffff"],
        stock: 50,
        device: "Dell Inspiron",
        installment: 85000,
        imageGallery: [mob3, mob2, mob2, mob3]
    },
    {
        id: 4,
        imageURL: iphone,
        price: "70,000 Rs.",
        name: "Lenovo IdeaPad 14 Intel Core i3 DDR4 4 GB HDD 1 TB",
        description: "Intel Core i7, DDR4, 16GB RAM, 512GB SSD",
        colors: ["#000000", "#ffffff"],
        stock: 200,
        device: "Dell Inspiron",
        installment: 9000,
        imageGallery: [mob2, mob3, mob2, mob3],
    },
    {
        id: 5,
        imageURL: laptop6,
        price: "50,000 Rs.",
        name: "Acer Aspire 5 Intel Core i3 DDR4 8 GB SSD 128 GB",
        description: "Intel Core i7, DDR4, 16GB RAM, 512GB SSD",
        colors: ["#000000", "#ffffff"],
        stock: 300,
         device: "Dell Inspiron",
         installment: 30280,
         
    },
    {
        id: 6,
        imageURL: laptop5,
        price: "180,000 Rs.",
        name: "Microsoft Surface Pro 7 Intel Core i5 DDR4 8 GB SSD 256 GB",
        description: "Intel Core i7, DDR4, 16GB RAM, 512GB SSD",
        colors: ["#000000", "#ffffff"],
        stock: 80,
         device: "Dell Inspiron",
         installment: 30000,
         imageGallery: [iphone, iphone, iphone, iphone],
    },
    {
        id: 7,
        imageURL: iphone,
        price: "140,000 Rs.",
        name: "Asus ZenBook 13 Intel Core i7 DDR4 16 GB SSD 1 TB",
        description: "Intel Core i7, DDR4, 16GB RAM, 512GB SSD",
        colors: ["#000000", "#ffffff"],
        stock: 120,
         device: "Dell Inspiron",
         installment: 30000,
         imageGallery: [iphone, iphone, iphone, iphone],
    },
    {
        id: 8,
        imageURL: laptop5,
        price: "60,000 Rs.",
        name: "Samsung Galaxy Book Intel Core i3 DDR4 8 GB SSD 256 GB",
        description: "Intel Core i7, DDR4, 16GB RAM, 512GB SSD",
        colors: ["#000000", "#ffffff"],
        stock: 400,
        imageGallery: [iphone, iphone, iphone, iphone],
    },
    {
        id: 9,
        imageURL: iphone,
        price: "200,000 Rs.",
        name: "iphone Air M1 Chip DDR4 16 GB SSD 512 GB",
        description: "Intel Core i7, DDR4, 16GB RAM, 512GB SSD",
        colors: ["#000000", "#ffffff"],
        stock: 50,
         device: "Dell Inspiron",
         imageGallery: [iphone, iphone, iphone, iphone],
    },
    {
        id: 10,
        imageURL: laptop6,
        price: "110,000 Rs.",
        name: "HP Spectre x360 Intel Core i5 DDR4 8 GB SSD 256 GB",
        description: "Intel Core i7, DDR4, 16GB RAM, 512GB SSD",
        colors: ["#000000", "#ffffff"],
        stock: 90,
         device: "Dell Inspiron",
         imageGallery: [iphone, iphone, iphone, iphone],
    },{
        id: 11,
        imageURL: iphone,
        price: "161,428 Rs.",
        name: "Apple iphone Pro 13\" 2.4 2019 Intel Core i5 DDR3 8 GB SSD 256 GB",
        description: "Intel Core i7, DDR4, 16GB RAM, 512GB SSD",
        colors: ["#000000", "#ffffff"],
        stock: 230,
         device: "Dell Inspiron",
         imageGallery: [iphone, iphone, iphone, iphone],
    },
    {
        id: 12,
        imageURL: iphone,
        price: "120,000 Rs.",
        name: "Dell Inspiron 15 Intel Core i7 DDR4 16 GB SSD 512 GB",
        description: "Intel Core i7, DDR4, 16GB RAM, 512GB SSD",
        colors: ["#000000", "#ffffff"],
        stock: 100,
         device: "Dell Inspiron",
         imageGallery: [iphone, iphone, iphone, iphone],
    },
    {
        id: 13,
        imageURL: laptop5,
        price: "90,000 Rs.",
        name: "HP Pavilion x360 Intel Core i5 DDR4 8 GB SSD 256 GB",
        description: "Intel Core i7, DDR4, 16GB RAM, 512GB SSD",
        colors: ["#000000", "#ffffff"],
        stock: 50,
         device: "Dell Inspiron",
         imageGallery: [iphone, iphone, iphone, iphone],
    },
    {
        id: 14,
        imageURL: iphone,
        price: "70,000 Rs.",
        name: "Lenovo IdeaPad 14 Intel Core i3 DDR4 4 GB HDD 1 TB",
        description: "Intel Core i7, DDR4, 16GB RAM, 512GB SSD",
        colors: ["#000000", "#ffffff"],
        stock: 200,
         device: "Dell Inspiron",
         imageGallery: [iphone, iphone, iphone, iphone],
    },
    {
        id: 15,
        imageURL: laptop5,
        price: "50,000 Rs.",
        name: "Acer Aspire 5 Intel Core i3 DDR4 8 GB SSD 128 GB",
        description: "Intel Core i7, DDR4, 16GB RAM, 512GB SSD",
        colors: ["#000000", "#ffffff"],
        stock: 300,
         device: "Dell Inspiron",
         imageGallery: [iphone, iphone, iphone, iphone],
    }
];
